import { env } from "./config/env.js";
import { logger } from "./logger/index.js";
import express from "express";
import helmet from "helmet";
import cors from "cors";
import session from "express-session";
import passport from "passport";
import RedisStore from "connect-redis";
import { redis } from "./redis/index.js";
import { prisma } from "./db/index.js";
import { scheduleRouter } from "./modules/schedule/router.js";
import { startOutboxRelay } from "./queue/outboxRelay.js";
import "./modules/auth/google.js";
import { requireAuth } from "./middleware/auth.js";
import { emailsRouter } from "./modules/emails/router.js";
import { batchesRouter } from "./modules/batches/router.js";
import { slackRouter } from "./modules/slack/router.js";
import { searchRouter } from "./modules/search/router.js";
import { sendersRouter } from "./modules/senders/router.js";
import { emailQueue,maintenanceQueue } from "./queue/emailQueue.js";
import { createBullBoard } from "@bull-board/api";
import { BullMQAdapter } from "@bull-board/api/bullMQAdapter";
import { ExpressAdapter } from "@bull-board/express";
import { elastic } from "./services/elastic.js";
import { randomUUID } from "node:crypto";
export const app = express();
app.use((req,res,next)=>{const requestId=randomUUID();res.setHeader("X-Request-Id",requestId);logger.child({requestId}).info({method:req.method,path:req.path},"Incoming request");next()});
app.use(helmet()); app.use(cors({ origin: env.FRONTEND_ORIGIN, credentials: true })); app.use(express.json({ limit: "1mb" }));
app.use(async(req,res,next)=>{try{const key=`api-limit:${req.ip}:${Math.floor(Date.now()/60000)}`;const count=await redis.incr(key);if(count===1)await redis.expire(key,60);if(count>env.API_RATE_LIMIT_PER_MINUTE){res.status(429).json({error:{code:"RATE_LIMITED",message:"Too many requests"}});return}next()}catch(error){next(error)}});
app.use(session({ store:new RedisStore({client:redis}),secret:env.SESSION_SECRET,resave:false,saveUninitialized:false,cookie:{httpOnly:true,sameSite:"lax",secure:env.NODE_ENV==="production",maxAge:7*24*60*60*1000} }));
app.use(passport.initialize()); app.use(passport.session());
app.get("/health", (_req, res) => res.json({ status: "ok" }));
app.get("/ready", async(_req,res)=>{try{await prisma.$queryRaw`SELECT 1`;await redis.ping();await elastic.ping();res.json({status:"ready"})}catch{res.status(503).json({status:"not_ready"})}});
app.get("/api/auth/google",passport.authenticate("google",{scope:["profile","email"]}));
app.get("/api/auth/google/callback",passport.authenticate("google",{failureRedirect:"/"}),(req,res)=>res.redirect(env.FRONTEND_ORIGIN));
app.get("/api/auth/me",(req,res)=>res.json({user:req.user??null}));
app.post("/api/auth/logout",(req,res)=>req.logout(error=>{if(error){res.status(500).json({error:{message:"Logout failed"}});return}req.session.destroy(()=>res.status(204).end())}));
app.use("/api/schedule",requireAuth,scheduleRouter); app.use("/api/emails",requireAuth,emailsRouter); app.use("/api/batches",requireAuth,batchesRouter);
app.use("/api/slack",slackRouter);
app.use("/api/emails/search",requireAuth,searchRouter);
app.use("/api/senders",requireAuth,sendersRouter);
app.get("/metrics",requireAuth,async(_req,res,next)=>{try{const [queue,sentLastHour,failed,rateLimitHits]=await Promise.all([emailQueue.getJobCounts("waiting","delayed","active","failed"),prisma.email.count({where:{status:"sent",sentAt:{gte:new Date(Date.now()-3600000)}}}),prisma.email.count({where:{status:"failed"}}),redis.get("rate-limit:hits")]);res.json({queue,sentLastHour,failed,rateLimitHits:Number(rateLimitHits??0)})}catch(error){next(error)}});
const boardAdapter=new ExpressAdapter();boardAdapter.setBasePath("/admin/queues");createBullBoard({queues:[new BullMQAdapter(emailQueue),new BullMQAdapter(maintenanceQueue)],serverAdapter:boardAdapter});app.use("/admin/queues",requireAuth,boardAdapter.getRouter());
app.use((error:unknown,_req:express.Request,res:express.Response,_next:express.NextFunction)=>{logger.error({error},"Request failed");res.status(500).json({error:{code:"INTERNAL_ERROR",message:"Request failed"}})});
const relay=process.env.NODE_ENV!=="test"?startOutboxRelay():undefined;
const server = process.env.NODE_ENV!=="test"?app.listen(env.PORT, () => logger.info({ port: env.PORT }, "API listening")):undefined;
let shuttingDown=false;
async function shutdown():Promise<void>{
  if(shuttingDown)return;shuttingDown=true;logger.info("API shutdown started");
  if(server)await new Promise<void>((resolve,reject)=>server.close(error=>error?reject(error):resolve()));
  if(relay)await (await relay).close();
  await Promise.all([emailQueue.close(),maintenanceQueue.close()]);
  await prisma.$disconnect();await redis.quit();await elastic.close();logger.info("API shutdown complete");
}
process.on("SIGTERM",()=>{void shutdown().then(()=>process.exit(0)).catch(error=>{logger.error({error},"API shutdown failed");process.exit(1)})});
process.on("SIGINT",()=>{void shutdown().then(()=>process.exit(0)).catch(error=>{logger.error({error},"API shutdown failed");process.exit(1)})});
