import { Router } from "express";
import { createHmac,randomBytes,timingSafeEqual } from "node:crypto";
import { env } from "../../config/env.js";
import { prisma } from "../../db/index.js";
import { requireAuth } from "../../middleware/auth.js";
import { encryptSecret } from "../../services/crypto.js";
export const slackRouter=Router();slackRouter.use(requireAuth);
function makeState(userId:string,nonce:string){const data=Buffer.from(JSON.stringify({userId,nonce,at:Date.now()})).toString("base64url");return `${data}.${createHmac("sha256",env.SESSION_SECRET).update(data).digest("base64url")}`}
function validState(state:string,userId:string,nonce:string){const [data,sig]=state.split(".");if(!data||!sig)return false;const expected=createHmac("sha256",env.SESSION_SECRET).update(data).digest();const actual=Buffer.from(sig,"base64url");if(actual.length!==expected.length||!timingSafeEqual(expected,actual))return false;const info=JSON.parse(Buffer.from(data,"base64url").toString()) as {userId:string;nonce:string;at:number};return info.userId===userId&&info.nonce===nonce&&Date.now()-info.at<600000}
slackRouter.get("/connect",(req,res)=>{if(!env.SLACK_CLIENT_ID||!env.SLACK_CLIENT_SECRET){res.status(503).json({error:{message:"Slack OAuth is not configured"}});return}const nonce=randomBytes(18).toString("hex");req.session.slackNonce=nonce;const url=new URL("https://slack.com/oauth/v2/authorize");url.searchParams.set("client_id",env.SLACK_CLIENT_ID);url.searchParams.set("scope","incoming-webhook");url.searchParams.set("redirect_uri",env.SLACK_CALLBACK_URL??`${env.API_PUBLIC_URL}/api/slack/callback`);url.searchParams.set("state",makeState((req.user as {id:string}).id,nonce));res.redirect(url.toString())});
slackRouter.get("/callback",async(req,res,next)=>{try{const userId=(req.user as {id:string}|undefined)?.id;if(!userId||!validState(String(req.query.state??""),userId,req.session.slackNonce??"")){res.status(403).json({error:{message:"Invalid OAuth state"}});return}const response=await fetch("https://slack.com/api/oauth.v2.access",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({code:String(req.query.code??""),client_id:env.SLACK_CLIENT_ID,client_secret:env.SLACK_CLIENT_SECRET,redirect_uri:env.SLACK_CALLBACK_URL??`${env.API_PUBLIC_URL}/api/slack/callback`})});const result=await response.json() as {ok:boolean;team?:{id:string;name:string};incoming_webhook?:{channel_id:string;url:string};error?:string};if(!result.ok||!result.incoming_webhook?.url||!result.team){res.status(400).json({error:{message:result.error??"Slack webhook setup failed"}});return}const data={teamId:result.team.id,teamName:result.team.name??"Slack",channelId:result.incoming_webhook.channel_id??"",encryptedCredential:encryptSecret(result.incoming_webhook.url)};await prisma.slackConnection.upsert({where:{userId},update:data,create:{userId,...data}});delete req.session.slackNonce;res.redirect(env.FRONTEND_ORIGIN)}catch(error){next(error)}});
slackRouter.get("/status",async(req,res,next)=>{try{const connection=await prisma.slackConnection.findUnique({where:{userId:(req.user as {id:string}).id},select:{teamName:true,channelId:true,connectedAt:true}});res.json({connected:!!connection,connection})}catch(error){next(error)}});
slackRouter.delete("/disconnect",async(req,res,next)=>{try{await prisma.slackConnection.deleteMany({where:{userId:(req.user as {id:string}).id}});res.status(204).end()}catch(error){next(error)}});
